### ISSUE TITLE
config.yaml

### ISSUE THREAD

**Issue by lakisharenee** [feder-cr/linkedIn_auto_jobs_applier_with_AI#174]
I'm getting the following error when I run the bot "Configuration error: Invalid type for key 'remote' in config file data_folder/config.yaml. Expected <class 'bool'>"

But, when I open up the folder, the code looks fine
"remote: true" 

Any suggestions?

Thanks!

**Comment by Ujjwal0919** [comment]
the error is might be because of the double quotes around remote:true. File should look like 
"remote: false

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: true
  month: true
  week: true
  24 hours: true

positions:
  - Cybersecurity Engineer

locations:
  - London
  - Manchester
  - Coventry
  - Cardiff
  - Birmingham
  - Reading
  - Bristol
  - Dubai
  - Dublin
  - Germany

distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist:
"

**Comment by lakisharenee** [comment]
This is cleared now. Now I'm getting the following "Runtime error: Error running the bot: AttributeError in experience_details processing: AttributeError in Experience: 'str' object has no attribute 'values'"

**Comment by lakisharenee** [comment]
I've figured out the other runtime error I mentioned in previous (now deleted) message. The program is running successfully.  Thank you so much!

**Comment by air55555** [comment]
@lakisharenee, did you solve? Than close the issue please.
