### ISSUE TITLE
Non related jobs application

### ISSUE THREAD

**Issue by AnassHmida** [feder-cr/linkedIn_auto_jobs_applier_with_AI#237]
i have set the work positions that i want to apply to , in my positions in config.yaml , but it seems that the bot is applying even to the job that linkedin is displaying when it searches for that role  , even though they don't have a relation to the job it self , for example the bot will search for "go developper" , the bot will apply to job in that pages that contain things like "android developer" "Rust engineer" and other roles that are displayed in that list

is there a way to stop this ?

**Comment by timeowilliams** [comment]
Hmm, @AnassHmida  > perhaps we should also add logic to check the title of each job in the list of jobs shown to and avoid clicking on jobs with un-related titles. 

I'm interested in roles that use javascript, but there are plenty of Mechanical Engineer jobs that will appear because the hiring team will add JavaScript _"someway & somehow"_ in the JD.

**Comment by feder-cr** [comment]
@AnassHmida yes for sure, you can workon this!
